name: Publish to PyPI

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v1.0, v2.3.4

jobs:
  publish-to-pypi:
    name: Publish Python Package to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/lybic
    permissions:
      id-token: write # Required for trusted publishing with OIDC

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      # This will check out the code at the specific tag that triggered the workflow

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install twine wheel setuptools build

    - name: Build package
      run: make build

    - name: Publish package to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.LYBIC_PYPI_KEY }}
      run: make publish
